"""
flow_models.py
===============
Model definitions for solving the source-localisation Bayesian Experimental Design (BED)
problem with *simulation-free Conditional Flow Matching* (CFM), extending the joint
policy + vector-field idea from the reference PDF.

Framing (see main.py docstring for the full derivation):

    We treat theta as being transported by a Continuous Normalizing Flow from a base
    point z0 ~ p(theta) (the *prior*) to a target point z1 = theta_true, where theta_true
    is the value that actually generated the (adaptively-chosen) history h_T = {(x_t, y_t)}.
    Because h_T was generated by simulating y_t ~ p(y | x_t, theta_true), theta_true is a
    valid sample of the posterior p(theta | h_T) induced by that particular sequence of
    designs. Training regresses a vector field v_theta(z_t, t, x_t, y_t) against the
    analytic velocity of a (possibly non-linear) interpolation path between z0 and z1,
    while a design-policy network pi_phi(z_t, t) -> x_t is trained *jointly*, end-to-end,
    through the same loss (the policy never sees z1 directly, so there is no "identity
    trap" as described in the PDF: the only way for the policy to reduce the loss is to
    pick designs x_t that make the resulting y_t informative about z1).

    We do NOT track an explicit Gaussian belief (mu, log_sigma) -- only a single point
    z_t per particle ("point" option). At generation time we integrate an ODE (Euler /
    Midpoint / diffrax Dopri5) from t=0 to t=1, sharing one realised design/outcome
    sequence across an ensemble of particles (each with an independent z0) to obtain
    approximate posterior samples theta | h_T at t=1, and to visualise an EIG-like proxy
    from how quickly the ensemble contracts.
"""
from __future__ import annotations

import math
from typing import Callable, NamedTuple, Tuple

import jax
import jax.numpy as jnp
import equinox as eqx
from jax import random

from models import SourceLocConfig, environment_step, sort_sources_by_amplitude

try:
    import diffrax
    _HAS_DIFFRAX = True
except ImportError:  # pragma: no cover
    _HAS_DIFFRAX = False


# ====================================================================================
# 1. Probability paths z_t (interpolation between z0 and z1) and their analytic velocity
# ====================================================================================
# Every path function has signature  path(z0, z1, t) -> (z_t, u_t)  where u_t = dz_t/dt
# is the ground-truth *target* velocity that the vector field regresses onto (Eq. 1-2 of
# the reference PDF, generalised beyond the straight-line Optimal-Transport path).
#
# Why bother with non-linear paths? The straight OT path spends its "velocity budget"
# uniformly over t in [0,1]. In an *adaptive* BED setting we would often like the flow to
# stay close to the prior while few observations have been collected (small t) and then
# contract quickly onto theta_true once informative designs have been played (large t)
# -- i.e. a path with more curvature near t=1. The `power` and `vp_trig` schedules below
# both allow this via a single interpretable knob.

def linear_path(z0: jnp.ndarray, z1: jnp.ndarray, t: jnp.ndarray) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """Standard Optimal-Transport / rectified-flow path: constant velocity."""
    z_t = (1.0 - t) * z0 + t * z1
    u_t = z1 - z0
    return z_t, u_t


def power_path(z0: jnp.ndarray, z1: jnp.ndarray, t: jnp.ndarray, power: float = 2.0
               ) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """z_t = (1 - t^p) z0 + t^p z1.

    power > 1: slow start / fast finish -> most of the transport happens near t=1
               (useful if you want the flow to "wait" for more designs before committing).
    power < 1: fast start / slow finish -> most of the transport happens near t=0.
    power = 1 recovers the linear path.
    """
    t_safe = jnp.clip(t, 1e-6, 1.0)
    s = t_safe ** power
    ds = power * t_safe ** (power - 1.0)
    z_t = (1.0 - s) * z0 + s * z1
    u_t = ds * (z1 - z0)
    return z_t, u_t


def vp_trig_path(z0: jnp.ndarray, z1: jnp.ndarray, t: jnp.ndarray) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """Trigonometric (variance-preserving-style) path: a quarter-circle interpolation.

    z_t = cos(pi/2 t) z0 + sin(pi/2 t) z1, which has zero velocity contribution from z1 at
    t=0 and zero contribution from z0 at t=1, with smooth (non-constant) curvature -- a
    softer alternative to `power_path` that avoids the singular derivative at t=0 that
    `power_path` has for power < 1.
    """
    c = jnp.cos(0.5 * jnp.pi * t)
    s = jnp.sin(0.5 * jnp.pi * t)
    dc = -0.5 * jnp.pi * jnp.sin(0.5 * jnp.pi * t)
    ds = 0.5 * jnp.pi * jnp.cos(0.5 * jnp.pi * t)
    z_t = c * z0 + s * z1
    u_t = dc * z0 + ds * z1
    return z_t, u_t


def get_path_fn(path_type: str, power: float = 2.0) -> Callable[[jnp.ndarray, jnp.ndarray, jnp.ndarray],
                                                                  Tuple[jnp.ndarray, jnp.ndarray]]:
    if path_type == "linear":
        return linear_path
    if path_type == "power":
        return lambda z0, z1, t: power_path(z0, z1, t, power=power)
    if path_type == "vp_trig":
        return vp_trig_path
    raise ValueError(f"Unknown path_type '{path_type}'. Choose from 'linear', 'power', 'vp_trig'.")


# ====================================================================================
# 2. Time embedding
# ====================================================================================
class TimeEmbedding(eqx.Module):
    """Fixed sinusoidal features of the scalar flow-time t, followed by a small trainable
    MLP (standard practice in diffusion / flow-matching models to give the network an
    easy-to-use, high-frequency representation of t)."""
    net: eqx.nn.MLP
    num_freqs: int = eqx.field(static=True)
    out_dim: int = eqx.field(static=True)

    def __init__(self, embed_dim: int = 32, num_freqs: int = 8, hidden: int = 32, *, key):
        self.num_freqs = num_freqs
        raw_dim = 2 * num_freqs + 1
        self.net = eqx.nn.MLP(raw_dim, embed_dim, hidden, depth=1, key=key)
        self.out_dim = embed_dim

    def _raw_features(self, t: jnp.ndarray) -> jnp.ndarray:
        freqs = jnp.arange(1, self.num_freqs + 1, dtype=jnp.float32)
        angles = t * freqs * jnp.pi
        return jnp.concatenate([jnp.sin(angles), jnp.cos(angles), jnp.array([t])])

    def __call__(self, t: jnp.ndarray) -> jnp.ndarray:
        return self.net(self._raw_features(t))


# ====================================================================================
# 3. Design policy pi_phi(z_t, t) -> x_t   (MLP, "inverse model")
# ====================================================================================
class DesignPolicyMLP(eqx.Module):
    """Produces the next sensor/query location x_t from the current flow state z_t and
    flow-time t. Crucially it never observes z1 (theta_true) -- it can only become
    informative by picking x_t that, combined with the (real, differentiable) simulator
    outcome y_t, helps the vector field regress the correct velocity."""
    time_embed: TimeEmbedding
    net: eqx.nn.MLP
    design_dim: int = eqx.field(static=True)
    design_bound: float = eqx.field(static=True)

    def __init__(self, theta_dim: int, design_dim: int, time_embed_dim: int = 32,
                 hidden: int = 128, depth: int = 3, design_bound: float = 4.0, *, key):
        k_t, k_net = random.split(key)
        self.time_embed = TimeEmbedding(embed_dim=time_embed_dim, key=k_t)
        self.net = eqx.nn.MLP(theta_dim + time_embed_dim, design_dim, hidden, depth=depth, key=k_net)
        self.design_dim = design_dim
        self.design_bound = design_bound

    def __call__(self, z_t: jnp.ndarray, t: jnp.ndarray) -> jnp.ndarray:
        te = self.time_embed(t)
        raw = self.net(jnp.concatenate([z_t, te], axis=-1))
        # Smooth bounding (tanh) rather than hard-clip so gradients don't vanish at the
        # boundary of the design space.
        return self.design_bound * jnp.tanh(raw)


# ====================================================================================
# 4. Vector field v_theta(z_t, t, x_t, y_t) -> velocity   (MLP, "forward model")
# ====================================================================================
class VectorFieldMLP(eqx.Module):
    """Regresses the instantaneous velocity of the flow, conditioned on the just-played
    design/outcome pair (x_t, y_t) -- i.e. a Markovian (memoryless) analogue of the
    'BayesSimulatorMLP' Bayes-update in the original LA-BED code, but now predicting a
    *velocity* rather than an additive belief update, so it can be integrated with any
    ODE solver (Euler / Midpoint / Dopri5) at generation time."""
    time_embed: TimeEmbedding
    net: eqx.nn.MLP
    theta_dim: int = eqx.field(static=True)

    def __init__(self, theta_dim: int, design_dim: int, obs_dim: int, time_embed_dim: int = 32,
                 hidden: int = 128, depth: int = 3, *, key):
        k_t, k_net = random.split(key)
        self.time_embed = TimeEmbedding(embed_dim=time_embed_dim, key=k_t)
        in_dim = theta_dim + time_embed_dim + design_dim + obs_dim
        self.net = eqx.nn.MLP(in_dim, theta_dim, hidden, depth=depth, key=k_net)
        self.theta_dim = theta_dim

    def __call__(self, z_t: jnp.ndarray, t: jnp.ndarray, x_t: jnp.ndarray, y_t: jnp.ndarray) -> jnp.ndarray:
        te = self.time_embed(t)
        inp = jnp.concatenate([z_t, te, x_t, y_t], axis=-1)
        return self.net(inp)


class FlowBEDModel(eqx.Module):
    """Container bundling the design policy and the vector field so both are updated
    jointly by a single optimiser (mirrors `LABEDModel` in the original main.py)."""
    policy: DesignPolicyMLP
    vector_field: VectorFieldMLP


def build_model(theta_dim: int, design_dim: int, obs_dim: int, *, key,
                 policy_hidden: int = 128, policy_depth: int = 3,
                 vf_hidden: int = 128, vf_depth: int = 3,
                 time_embed_dim: int = 32, design_bound: float = 4.0) -> FlowBEDModel:
    k_p, k_v = random.split(key)
    policy = DesignPolicyMLP(theta_dim, design_dim, time_embed_dim=time_embed_dim,
                              hidden=policy_hidden, depth=policy_depth,
                              design_bound=design_bound, key=k_p)
    vector_field = VectorFieldMLP(theta_dim, design_dim, obs_dim, time_embed_dim=time_embed_dim,
                                   hidden=vf_hidden, depth=vf_depth, key=k_v)
    return FlowBEDModel(policy=policy, vector_field=vector_field)


# ====================================================================================
# 5. Design regularisers (placeholders -- see main.py --design-reg flag)
# ====================================================================================
def design_regularizer(x_t: jnp.ndarray, kind: str = "none") -> jnp.ndarray:
    """Optional penalty/bonus added to the flow-matching loss to explicitly shape the
    designs x_t towards being more informative (maximising EIG), on top of whatever
    informativeness pressure already comes "for free" through the joint flow-matching
    objective (see module docstring). Currently only 'none' (a no-op) is implemented --
    the joint objective already avoids the PDF's "Identity Trap" since pi_phi never sees
    z1. Good candidates to implement here if the plain joint loss under-explores:

      - 'mine'              : an auxiliary MINE (Belghazi et al., 2018) critic
                               T_psi(x_t, y_t, z_t) lower-bounding I(theta ; y_t | x_t),
                               added as -I_hat to the loss so the policy is pushed to
                               maximise mutual information directly.
      - 'dad_eig'            : a contrastive lower bound on EIG in the style of Deep
                               Adaptive Design (Foster et al., 2021): sample several
                               alternative thetas from the batch, contrast
                               log p(y_t | x_t, theta_true) against log p(y_t | x_t, theta').
      - 'ensemble_repulsion' : run a small ensemble of z0 particles through the vector
                               field with a *shared* x_t and penalise low variance in
                               their predicted velocities -- a cheap proxy for "this
                               design does not discriminate between plausible thetas".
      - 'entropy_bonus'      : penalise low entropy of the batch-level design
                               distribution p(x_t) to discourage the policy collapsing
                               onto a constant / fixed sensor location.
      - 'coverage'           : an L2 repulsion term across a trajectory's designs x_{1:T}
                               (or across a batch) encouraging spatial coverage instead
                               of clustering.
    """
    if kind == "none":
        return jnp.array(0.0)
    raise NotImplementedError(
        f"design_regularizer(kind='{kind}') is not implemented yet -- see the docstring "
        "for suggested approaches; contributions welcome."
    )


# ====================================================================================
# 6. Generation-time ODE integration (Euler / Midpoint / diffrax Dopri5)
# ====================================================================================
class RolloutResult(NamedTuple):
    ts: jnp.ndarray          # (T+1,)              flow-time grid (including t=0 and t=1)
    z_ensemble: jnp.ndarray  # (T+1, M, theta_dim)  ensemble state at each grid point
    designs: jnp.ndarray     # (T, design_dim)      realised designs x_t
    outcomes: jnp.ndarray    # (T, obs_dim)          realised outcomes y_t
    nfe: int                 # number of vector-field evaluations (solver cost)


def _shared_design_and_outcome(model: FlowBEDModel, z_ensemble: jnp.ndarray, t: jnp.ndarray,
                                theta_true_sorted: jnp.ndarray, cfg: SourceLocConfig, key
                                ) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """A single *physical* design/outcome is shared across the whole ensemble at flow-time
    t (only one real experiment happens at any given t); the design is computed from the
    ensemble mean, which acts as the running point-estimate of theta."""
    z_mean = z_ensemble.mean(axis=0)
    x_t = model.policy(z_mean, t)
    y_t = environment_step(theta_true_sorted, x_t, key, cfg)
    return x_t, y_t


def euler_rollout(model: FlowBEDModel, theta_true_sorted: jnp.ndarray, key,
                   cfg: SourceLocConfig, num_particles: int, num_steps: int,
                   theta_dim: int, prior_std: float) -> RolloutResult:
    key, z0_key = random.split(key)
    z0 = prior_std * random.normal(z0_key, (num_particles, theta_dim))
    dt = 1.0 / num_steps
    ts = jnp.linspace(0.0, 1.0, num_steps + 1)
    step_keys = random.split(key, num_steps)

    def scan_fn(z, inp):
        t, sk = inp
        x_t, y_t = _shared_design_and_outcome(model, z, t, theta_true_sorted, cfg, sk)
        v = jax.vmap(lambda zi: model.vector_field(zi, t, x_t, y_t))(z)
        z_next = z + dt * v
        return z_next, (z_next, x_t, y_t)

    z_final, (z_traj, xs, ys) = jax.lax.scan(scan_fn, z0, (ts[:-1], step_keys))
    z_ensemble = jnp.concatenate([z0[None], z_traj], axis=0)
    return RolloutResult(ts=ts, z_ensemble=z_ensemble, designs=xs, outcomes=ys, nfe=num_steps)


def midpoint_rollout(model: FlowBEDModel, theta_true_sorted: jnp.ndarray, key,
                      cfg: SourceLocConfig, num_particles: int, num_steps: int,
                      theta_dim: int, prior_std: float) -> RolloutResult:
    """Classic RK2 (midpoint) integrator. Each output step costs two vector-field /
    simulator evaluations (one at t, one at t + dt/2); both are legitimate *in-silico*
    simulator calls (the simulator always conditions on the true theta), not physical
    experiments, so this is consistent with a simulation-based-inference training regime."""
    key, z0_key = random.split(key)
    z0 = prior_std * random.normal(z0_key, (num_particles, theta_dim))
    dt = 1.0 / num_steps
    ts = jnp.linspace(0.0, 1.0, num_steps + 1)
    step_keys = random.split(key, num_steps * 2).reshape(num_steps, 2, -1)

    def scan_fn(z, inp):
        t, sk = inp
        sk1, sk2 = sk[0], sk[1]
        x1, y1 = _shared_design_and_outcome(model, z, t, theta_true_sorted, cfg, sk1)
        k1 = jax.vmap(lambda zi: model.vector_field(zi, t, x1, y1))(z)
        z_mid = z + 0.5 * dt * k1
        t_mid = t + 0.5 * dt
        x2, y2 = _shared_design_and_outcome(model, z_mid, t_mid, theta_true_sorted, cfg, sk2)
        k2 = jax.vmap(lambda zi: model.vector_field(zi, t_mid, x2, y2))(z_mid)
        z_next = z + dt * k2
        # report the *first-stage* design/outcome as the "realised" one for visualisation
        return z_next, (z_next, x1, y1)

    z_final, (z_traj, xs, ys) = jax.lax.scan(scan_fn, z0, (ts[:-1], step_keys))
    z_ensemble = jnp.concatenate([z0[None], z_traj], axis=0)
    return RolloutResult(ts=ts, z_ensemble=z_ensemble, designs=xs, outcomes=ys, nfe=num_steps * 2)


def dopri5_rollout(model: FlowBEDModel, theta_true_sorted: jnp.ndarray, key,
                    cfg: SourceLocConfig, num_particles: int, num_steps: int,
                    theta_dim: int, prior_std: float,
                    rtol: float = 1e-3, atol: float = 1e-5, max_steps: int = 4096) -> RolloutResult:
    """Adaptive-step Dopri5 (Runge-Kutta 4(5)) integration via `diffrax`. Because diffrax
    may query the vector field at arbitrary (and possibly repeated) times during error
    control, the "physical" design/outcome pair at flow-time t is made a deterministic
    function of t by folding a quantised version of t into the base PRNG key -- i.e. we
    treat each nominal flow-time as a fixed, reproducible in-silico experiment."""
    if not _HAS_DIFFRAX:
        raise ImportError("diffrax is not installed. Run `pip install diffrax` to use the "
                           "'dopri5' solver, or choose 'euler' / 'midpoint' instead.")
    key, z0_key, base_key = random.split(key, 3)
    z0 = prior_std * random.normal(z0_key, (num_particles, theta_dim))

    def vf(t, z, args):
        z_mean = z.mean(axis=0)
        x_t = model.policy(z_mean, t)
        key_t = random.fold_in(base_key, jnp.int32(t * 1_000_000))
        y_t = environment_step(theta_true_sorted, x_t, key_t, cfg)
        return jax.vmap(lambda zi: model.vector_field(zi, t, x_t, y_t))(z)

    term = diffrax.ODETerm(vf)
    solver = diffrax.Dopri5()
    ts = jnp.linspace(0.0, 1.0, num_steps + 1)
    saveat = diffrax.SaveAt(ts=ts)
    controller = diffrax.PIDController(rtol=rtol, atol=atol)
    sol = diffrax.diffeqsolve(term, solver, t0=0.0, t1=1.0, dt0=1.0 / num_steps, y0=z0,
                               saveat=saveat, stepsize_controller=controller, max_steps=max_steps)
    z_ensemble = sol.ys  # (T+1, M, theta_dim)

    # Recompute the realised design/outcome at each saved grid point (excluding t=1) for
    # visualisation purposes only -- deterministic given the same base_key.
    def recompute(z, t):
        z_mean = z.mean(axis=0)
        x_t = model.policy(z_mean, t)
        key_t = random.fold_in(base_key, jnp.int32(t * 1_000_000))
        y_t = environment_step(theta_true_sorted, x_t, key_t, cfg)
        return x_t, y_t

    xs, ys = jax.vmap(recompute)(z_ensemble[:-1], ts[:-1])
    nfe = int(sol.stats["num_steps"]) if isinstance(sol.stats.get("num_steps"), (int, float)) else num_steps
    return RolloutResult(ts=ts, z_ensemble=z_ensemble, designs=xs, outcomes=ys, nfe=nfe)


SOLVERS = {"euler": euler_rollout, "midpoint": midpoint_rollout, "dopri5": dopri5_rollout}


def run_rollout(solver: str, model: FlowBEDModel, theta_true_sorted: jnp.ndarray, key,
                 cfg: SourceLocConfig, num_particles: int, num_steps: int,
                 theta_dim: int, prior_std: float) -> RolloutResult:
    if solver not in SOLVERS:
        raise ValueError(f"Unknown solver '{solver}'. Choose from {list(SOLVERS)}.")
    return SOLVERS[solver](model, theta_true_sorted, key, cfg, num_particles, num_steps,
                            theta_dim, prior_std)


# ====================================================================================
# 7. EIG proxy from ensemble contraction
# ====================================================================================
def ensemble_uncertainty(z_ensemble: jnp.ndarray, eps: float = 1e-6) -> jnp.ndarray:
    """Sum of per-dimension log-std across the ensemble at each saved flow-time -- a cheap
    proxy for the (unnormalised) differential entropy of a Gaussian fit to the ensemble,
    playing the role that `belief_entropy` played for the explicit-Gaussian-belief model.
    z_ensemble: (T+1, M, theta_dim) -> returns (T+1,)."""
    std = jnp.std(z_ensemble, axis=1) + eps  # (T+1, theta_dim)
    return jnp.sum(jnp.log(std), axis=-1)


def eig_per_step(z_ensemble: jnp.ndarray) -> jnp.ndarray:
    """Entropy-reduction proxy for EIG at each of the T realised design/outcome steps."""
    unc = ensemble_uncertainty(z_ensemble)
    return unc[:-1] - unc[1:]
