# %% [markdown]
# # Conditional-Flow-Matching Bayesian Experimental Design (CFM-BED)
# ### Source localisation, run as a cell-by-cell notebook (VS Code / Jupyter `# %%` cells)
#
# --------------------------------------------------------------------------------------
# ### Why flow matching, and how it differs from the reference PDF
# --------------------------------------------------------------------------------------
# The reference PDF ("Joint Training of Policies and Continuous Normalizing Flows via
# Conditional Flow Matching") sketches a policy `pi_phi(z_t, z)` that observes the
# *final* target `z` and progressively reveals information about it to a vector field
# `v_theta`. That formulation is too simple for BED: in a real experiment-design loop,
# nothing ever observes the true parameter theta directly -- the policy can only choose
# a design `x_t`, and the environment returns a noisy outcome `y_t = p(y | x_t, theta_true)`.
#
# We adapt the recipe as follows:
#
#   * The **base distribution** of the flow is the experiment's prior `p(theta)` itself
#     (not a generic `N(0, I)`): `z0 ~ p(theta)`.
#   * The **target** `z1` is `theta_true`, the parameter that actually generated the
#     episode. Because every `y_t` along the episode was generated by the *true*
#     simulator conditioned on `theta_true` (never resampled from a model), `theta_true`
#     is, by construction, a valid draw from the posterior `p(theta | h_T)` induced by
#     that particular sequence of designs/outcomes `h_T = {(x_t, y_t)}`. Training the
#     flow to map `z0 -> theta_true` is therefore exactly amortised posterior sampling,
#     in the spirit of (sequential) neural posterior estimation / SBI.
#   * The **policy** `pi_phi(z_t, t) -> x_t` only ever sees the *current* flow state
#     `z_t` and the flow-time `t` -- never `z1` -- so there is no "Identity Trap": the
#     only way the policy can lower the joint flow-matching loss is by choosing designs
#     whose resulting (real, differentiable) outcome `y_t` actually helps the vector
#     field predict the correct velocity. Gradients flow `loss -> v_theta -> x_t -> pi_phi`
#     end-to-end.
#   * Training is **simulation-free**, exactly in the sense of the PDF's Algorithm 1: for
#     each training example we sample a single random flow-time `t ~ U(0,1)`, evaluate
#     the interpolated state `z_t` analytically along a chosen probability path (not
#     necessarily the straight OT line -- see `flow_models.get_path_fn`), and regress the
#     vector field against the path's analytic velocity. No ODE solve is needed at train
#     time.
#   * We use the **"point" representation only** (no explicit Gaussian belief /
#     log-sigma): each particle is transported as a single point, matching the request
#     that we move one sample from the prior to one sample of the posterior.
#   * At **generation time** (evaluation/visualisation) we integrate an ODE from `t=0` to
#     `t=1`. Three solvers are supported: `'euler'`, `'midpoint'` (hand-rolled via
#     `jax.lax.scan`), and `'dopri5'` (adaptive Runge-Kutta via `diffrax`). To visualise
#     an EIG-like quantity without an explicit belief, we integrate an *ensemble* of
#     particles (independent `z0` draws) that all share the *same* realised
#     design/outcome sequence (the design at each flow-time is computed from the
#     ensemble mean, since only one design can physically be queried at a time) and track
#     how the ensemble's spread contracts over flow-time -- see `flow_models.eig_per_step`.
#
# --------------------------------------------------------------------------------------
# ### Reproducibility
# --------------------------------------------------------------------------------------
# * `cfg.data_mode = "finite"` (default) pre-generates the *entire* fixed pool of
#   `cfg.n_train_episodes` seeds up front (see `datalloaders.FiniteEpisodes`); one epoch
#   is then a genuine, seeded-shuffle traversal of that whole pool, not an arbitrary
#   number of steps. `cfg.steps_per_epoch` is therefore only used in `data_mode="infinite"`.
# * Everything downstream (model init, per-step batch keys, environment noise) is a
#   deterministic function of `cfg.seed`, so two runs with the same `cfg` (and the same
#   XLA/hardware backend) produce identical results.
# * On GPU, a handful of JAX ops are not bit-exactly deterministic by default; set
#   `os.environ["XLA_FLAGS"] = "--xla_gpu_deterministic_ops=true"` before importing jax
#   if you need bit-exact reproducibility there too. CPU execution is deterministic as-is.
#
# --------------------------------------------------------------------------------------
# ### How to use this file
# --------------------------------------------------------------------------------------
# Run the cells top to bottom. `cfg = Config()` uses sensible defaults for a first run;
# edit any field on `cfg` in that cell before running the rest (e.g. `cfg.epochs = 5`).
# Set `cfg.train = False` to skip training entirely and only load + evaluate/visualise an
# existing checkpoint (see `find_checkpoint` -- it looks next to this script first, which
# is where a training run copies itself, so re-running the copied script from inside its
# own `runs/<timestamp>/` folder with `cfg.train = False` "just works").

# %%
import json
import shutil
from dataclasses import asdict, dataclass
from datetime import datetime
from itertools import permutations
from pathlib import Path
from typing import Optional
from itertools import permutations

import jax
import jax.numpy as jnp
import equinox as eqx
import optax
import numpy as np
import matplotlib.pyplot as plt
from tqdm.auto import tqdm

try:
    import seaborn as sns
    sns.set_theme(style="whitegrid", rc={"figure.facecolor": "white", "axes.facecolor": "white"})
except ImportError:
    pass

from models import SourceLocConfig, sort_sources_by_amplitude, environment_step
from datalloaders import SourceLocPrior, make_train_loader, make_eval_loader
from flow_models import (
    build_model, FlowBEDModel, get_path_fn, design_regularizer,
    run_rollout, eig_per_step, RolloutResult, _HAS_DIFFRAX,
)

THIS_FILE = Path.cwd() / "main.py"  # override below if this file lives elsewhere
if "__file__" in dir():
    THIS_FILE = Path(__file__).resolve()
THIS_DIR = THIS_FILE.parent


# %% [markdown]
# ## 1. Config

# %%
@dataclass
class Config:
    # --- run control -----------------------------------------------------------------
    train: bool = True
    run_dir: Optional[str] = None      # existing run to load a checkpoint from
    checkpoint: Optional[str] = None   # explicit checkpoint path override
    seed: int = 2026

    # --- problem / environment ---------------------------------------------------------
    k_sources: int = 2
    design_dim: int = 2
    obs_dim: int = 1
    prior_std: float = 1.0
    env_b: float = 0.1
    env_m: float = 1e-4
    env_A: float = 1.0
    env_sigma: float = 0.5

    # --- flow matching -------------------------------------------------------------
    path_type: str = "linear"     # "linear" | "power" | "vp_trig"
    path_power: float = 2.0       # only used when path_type == "power"
    design_reg: str = "none"      # see flow_models.design_regularizer
    design_reg_weight: float = 1.0
    design_bound: float = 4.0

    # --- architecture ------------------------------------------------------------------
    time_embed_dim: int = 32
    policy_hidden: int = 128
    policy_depth: int = 3
    vf_hidden: int = 128
    vf_depth: int = 3

    # --- optimisation --------------------------------------------------------------
    batch_size: int = 64
    epochs: int = 10
    lr: float = 1e-3

    # Training-data regime -- see the reproducibility note above / datalloaders.py.
    data_mode: str = "infinite"        # "finite" (recommended) | "infinite"
    n_train_episodes: int = 200_000  # size of the fixed, reproducible pool (finite mode)
    steps_per_epoch: int = 1000      # only used when data_mode == "infinite"

    # --- generation / evaluation ------------------------------------------------------
    num_design_steps: int = 30     # T: number of realised design/outcome steps at gen time
    num_particles: int = 64        # ensemble size for posterior sampling / EIG proxy
    solver: str = "euler"          # "euler" | "midpoint" | "dopri5"
    n_eval_episodes: int = 21
    n_viz_episodes: int = 1        # how many eval episodes to plot in detail

    @property
    def theta_dim(self) -> int:
        return self.k_sources * 2


## Use the default config from the dataclass
cfg = Config()

## To customise a run, just set fields directly, e.g.:
# cfg.epochs = 5
# cfg.k_sources = 1
# cfg.path_type = "power"; cfg.path_power = 2.0
# cfg.solver = "dopri5"
# cfg.train = False   # only load + evaluate an existing checkpoint

# def config_from_args(args: argparse.Namespace) -> Config:
#     cfg = Config()
#     for f in cfg.__dataclass_fields__:
#         if hasattr(args, f) and getattr(args, f) is not None:
#             setattr(cfg, f, getattr(args, f))
#     return cfg


# def build_argparser() -> argparse.ArgumentParser:
#     p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
#     p.add_argument("--train", type=lambda s: s.lower() in ("1", "true", "yes", "y"), default=True,
#                    help="Train a new model (default true). Set false to only load+evaluate.")
#     p.add_argument("--run-dir", dest="run_dir", type=str, default=None,
#                    help="Existing run directory to load a checkpoint from (required-ish if --train false).")
#     p.add_argument("--checkpoint", type=str, default=None, help="Explicit checkpoint file override.")
#     p.add_argument("--seed", type=int, default=None)
#     p.add_argument("--k-sources", dest="k_sources", type=int, default=None)
#     p.add_argument("--path-type", dest="path_type", type=str, default=None, choices=["linear", "power", "vp_trig"])
#     p.add_argument("--path-power", dest="path_power", type=float, default=None)
#     p.add_argument("--design-reg", dest="design_reg", type=str, default=None)
#     p.add_argument("--batch-size", dest="batch_size", type=int, default=None)
#     p.add_argument("--epochs", type=int, default=None)
#     p.add_argument("--steps-per-epoch", dest="steps_per_epoch", type=int, default=None)
#     p.add_argument("--lr", type=float, default=None)
#     p.add_argument("--num-design-steps", dest="num_design_steps", type=int, default=None)
#     p.add_argument("--num-particles", dest="num_particles", type=int, default=None)
#     p.add_argument("--solver", type=str, default=None, choices=["euler", "midpoint", "dopri5"])
#     p.add_argument("--n-eval-episodes", dest="n_eval_episodes", type=int, default=None)
#     return p


# %% [markdown]
# ## 2. Run-folder management & (de)serialisation helpers

# %%
def make_run_dir(base: Path = THIS_DIR / "runs") -> Path:
    stamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    run_dir = base / stamp
    (run_dir / "plots").mkdir(parents=True, exist_ok=True)
    return run_dir


def snapshot_code(run_dir: Path) -> None:
    """Copy this script and its sibling modules into the run dir for provenance, so the
    run is fully reproducible (and re-running `main.py` *from inside* the run dir with
    `cfg.train = False` picks up its own checkpoint automatically)."""
    for name in ("main.py", "flow_models.py", "models.py", "datalloaders.py"):
        src = THIS_DIR / name
        if src.exists():
            shutil.copy2(src, run_dir / name)


def find_checkpoint(cfg: Config) -> Path:
    candidates = []
    if cfg.checkpoint:
        candidates.append(Path(cfg.checkpoint))
    if cfg.run_dir:
        candidates.append(Path(cfg.run_dir) / "checkpoint.eqx")
    # running from a copied run folder: checkpoint sits right next to this script
    candidates.append(THIS_DIR / "checkpoint.eqx")
    # fall back: most recent run under runs/
    runs_base = THIS_DIR / "runs"
    if runs_base.exists():
        runs = sorted([d for d in runs_base.iterdir() if d.is_dir()], reverse=True)
        candidates.extend([d / "checkpoint.eqx" for d in runs])
    for c in candidates:
        if c.exists():
            return c
    raise FileNotFoundError(
        "No checkpoint found. Set cfg.checkpoint or cfg.run_dir explicitly, or train a "
        "model first with cfg.train = True."
    )


def save_config(cfg: Config, run_dir: Path) -> None:
    with open(run_dir / "config.json", "w") as f:
        json.dump(asdict(cfg), f, indent=2)


def load_config(run_dir: Path) -> Config:
    with open(Path(run_dir) / "config.json") as f:
        d = json.load(f)
    loaded = Config()
    for k, v in d.items():
        if hasattr(loaded, k):
            setattr(loaded, k, v)
    return loaded


def save_model(model: FlowBEDModel, path: Path) -> None:
    eqx.tree_serialise_leaves(str(path), model)


def load_model(cfg: Config, path: Path, key) -> FlowBEDModel:
    skeleton = build_model(cfg.theta_dim, cfg.design_dim, cfg.obs_dim, key=key,
                            policy_hidden=cfg.policy_hidden, policy_depth=cfg.policy_depth,
                            vf_hidden=cfg.vf_hidden, vf_depth=cfg.vf_depth,
                            time_embed_dim=cfg.time_embed_dim, design_bound=cfg.design_bound)
    return eqx.tree_deserialise_leaves(str(path), skeleton)


# %% [markdown]
# ## 3. Set up run directory / load checkpoint, and build (or load) the model

# %%
key = jax.random.PRNGKey(cfg.seed)
key, model_key = jax.random.split(key)

if cfg.train:
    run_dir = make_run_dir()
    snapshot_code(run_dir)
    save_config(cfg, run_dir)
    print(f"Run directory: {run_dir}")

    sim_cfg = SourceLocConfig(K=cfg.k_sources, b=cfg.env_b, m=cfg.env_m, A=cfg.env_A, sigma=cfg.env_sigma)
    model = build_model(cfg.theta_dim, cfg.design_dim, cfg.obs_dim, key=model_key,
                         policy_hidden=cfg.policy_hidden, policy_depth=cfg.policy_depth,
                         vf_hidden=cfg.vf_hidden, vf_depth=cfg.vf_depth,
                         time_embed_dim=cfg.time_embed_dim, design_bound=cfg.design_bound)
else:
    ckpt_path = find_checkpoint(cfg)
    run_dir = ckpt_path.parent
    if (run_dir / "config.json").exists():
        saved_cfg = load_config(run_dir)
        saved_cfg.train = False
        # allow overriding eval-time-only knobs on top of the saved (training) config
        saved_cfg.solver = cfg.solver
        saved_cfg.num_design_steps = cfg.num_design_steps
        saved_cfg.num_particles = cfg.num_particles
        saved_cfg.n_eval_episodes = cfg.n_eval_episodes
        saved_cfg.n_viz_episodes = cfg.n_viz_episodes
        cfg = saved_cfg
    print(f"Loading checkpoint: {ckpt_path}")
    sim_cfg = SourceLocConfig(K=cfg.k_sources, b=cfg.env_b, m=cfg.env_m, A=cfg.env_A, sigma=cfg.env_sigma)
    model = load_model(cfg, ckpt_path, model_key)


# %% [markdown]
# ## 4. Training loss (simulation-free flow matching, Algorithm 1 of the PDF, adapted)

# %%
def make_loss_fn(cfg: Config, sim_cfg: SourceLocConfig):
    path_fn = get_path_fn(cfg.path_type, power=cfg.path_power)

    def per_example_loss(model: FlowBEDModel, theta_true: jnp.ndarray, key):
        k_z0, k_t, k_env = jax.random.split(key, 3)

        theta_true_sorted = sort_sources_by_amplitude(theta_true, sim_cfg)  # canonicalise
        z1 = theta_true_sorted.reshape(-1)
        z0 = cfg.prior_std * jax.random.normal(k_z0, (cfg.theta_dim,))
        t = jax.random.uniform(k_t, ())

        z_t, u_t = path_fn(z0, z1, t)

        x_t = model.policy(z_t, t)
        y_t = environment_step(theta_true_sorted, x_t, k_env, sim_cfg)

        v_hat = model.vector_field(z_t, t, x_t, y_t)
        flow_mse = jnp.mean((v_hat - u_t) ** 2)

        # ## Let's permute the velocities u_t, and the minimum MSE over all permutations is the loss. This is permutation-invariant, since the sources are unordered.
        # perm_indices = jnp.array(list(permutations(range(cfg.k_sources)))) #Shape: (K!, K)
        # for perm in perm_indices:
        #     perm = jnp.array(perm)
        #     perm = jnp.repeat(perm, 2) #Shape: (2K,)
        #     u_t_perm = u_t[perm]
        #     flow_mse_perm = jnp.mean((v_hat - u_t_perm) ** 2)
        #     if 'flow_mse' not in locals():
        #         flow_mse = flow_mse_perm
        #     else:
        #         flow_mse = jnp.minimum(flow_mse, flow_mse_perm)

        reg = design_regularizer(x_t, kind=cfg.design_reg)
        loss = flow_mse + cfg.design_reg_weight * reg
        return loss, flow_mse

    @eqx.filter_value_and_grad(has_aux=True)
    def loss_fn(model: FlowBEDModel, theta_batch: jnp.ndarray, key):
        keys = jax.random.split(key, theta_batch.shape[0])
        losses, flow_mses = jax.vmap(per_example_loss, in_axes=(None, 0, 0))(model, theta_batch, keys)
        return jnp.mean(losses), {"flow_mse": jnp.mean(flow_mses)}

    return loss_fn


def make_train_step(cfg: Config, sim_cfg: SourceLocConfig, optimizer: optax.GradientTransformation):
    loss_fn = make_loss_fn(cfg, sim_cfg)

    @eqx.filter_jit
    def train_step(model, opt_state, theta_batch, key):
        (loss, aux), grads = loss_fn(model, theta_batch, key)
        updates, opt_state = optimizer.update(grads, opt_state, model)
        model = eqx.apply_updates(model, updates)
        return model, opt_state, loss, aux

    return train_step


# %% [markdown]
# ## 5. Training loop
#
# `data_mode="finite"` (default): one epoch = one full, seeded-shuffle pass over the
# fixed pool of `cfg.n_train_episodes` pre-seeded episodes (`len(train_loader)` batches).
# `data_mode="infinite"`: one epoch = `cfg.steps_per_epoch` freshly streamed batches.

# %%
def train(cfg: Config, sim_cfg: SourceLocConfig, model: FlowBEDModel, key, run_dir: Path):
    prior = SourceLocPrior(K=cfg.k_sources, prior_std=cfg.prior_std)
    train_loader = make_train_loader(prior, cfg.batch_size, base_seed=cfg.seed,
                                      data_mode=cfg.data_mode, n_train_episodes=cfg.n_train_episodes)

    optimizer = optax.adam(cfg.lr)
    opt_state = optimizer.init(eqx.filter(model, eqx.is_array))
    train_step = make_train_step(cfg, sim_cfg, optimizer)

    epoch_losses, step_losses, step_flow_mses = [], [], []
    infinite_iter = iter(train_loader) if cfg.data_mode == "infinite" else None

    print("Starting training...")
    for epoch in range(cfg.epochs):
        if cfg.data_mode == "finite":
            batch_source = train_loader          # full, reproducible pass = one epoch
            n_batches = len(train_loader)
        else:
            n_batches = cfg.steps_per_epoch
            batch_source = (next(infinite_iter) for _ in range(n_batches))

        running, n_steps = 0.0, 0
        pbar = tqdm(batch_source, total=n_batches, desc=f"Epoch {epoch + 1}/{cfg.epochs}")
        for theta_batch_np in pbar:
            key, batch_key = jax.random.split(key)
            theta_batch = jnp.asarray(theta_batch_np)
            model, opt_state, loss_val, aux = train_step(model, opt_state, theta_batch, batch_key)
            loss_f = float(loss_val)
            running += loss_f
            n_steps += 1
            step_losses.append(loss_f)
            step_flow_mses.append(float(aux["flow_mse"]))
            pbar.set_postfix(loss=f"{loss_f:.4f}")

        avg = running / max(n_steps, 1)
        epoch_losses.append(avg)
        print(f"Epoch {epoch + 1} average loss: {avg:.4f} ({n_steps} steps)")

        # checkpoint every epoch so partial progress is never lost
        save_model(model, run_dir / "checkpoint.eqx")

    history = {"epoch_losses": epoch_losses, "step_losses": step_losses, "step_flow_mses": step_flow_mses}
    with open(run_dir / "train_history.json", "w") as f:
        json.dump(history, f)
    return model, history, key


# %%
if cfg.train:
    model, history, key = train(cfg, sim_cfg, model, key, run_dir)
    save_model(model, run_dir / "checkpoint.eqx")
else:
    history = None
    if (run_dir / "train_history.json").exists():
        with open(run_dir / "train_history.json") as f:
            history = json.load(f)


# %% [markdown]
# ## 6. Training curves (shown here, then saved)

# %%
def plot_training_curves(history: dict):
    fig, ax = plt.subplots(2, 1, figsize=(10, 8))
    ax[0].plot(range(1, len(history["epoch_losses"]) + 1), history["epoch_losses"], marker="o", color="purple")
    ax[0].set_title("Flow-Matching Loss per Epoch")
    ax[0].set_xlabel("Epoch"); ax[0].set_ylabel("Loss"); ax[0].set_yscale("symlog"); ax[0].grid(alpha=0.3)

    ax[1].plot(range(1, len(history["step_losses"]) + 1), history["step_losses"], color="orange", lw=0.7)
    ax[1].set_title("Flow-Matching Loss per Step")
    ax[1].set_xlabel("Training Step"); ax[1].set_ylabel("Loss"); ax[1].set_yscale("symlog"); ax[1].grid(alpha=0.3)
    fig.tight_layout()
    return fig


if history is not None:
    fig = plot_training_curves(history)
    plt.show()
    fig.savefig(run_dir / "plots" / "training_curves.png", dpi=150)
    plt.close(fig)


# %% [markdown]
# ## 7. Evaluation
#
# For each held-out episode we roll out an ensemble of particles (see module docstring)
# under `cfg.solver`, and score the ensemble-mean at `t=1` against `theta_true` using the
# best-permutation MSE (permutation-invariant since sources are unordered).

# %%
def best_permutation_mse(pred: np.ndarray, true: np.ndarray, K: int) -> float:
    pred = pred.reshape(K, 2)
    true = true.reshape(K, 2)
    best = np.inf
    for perm in permutations(range(K)):
        mse = float(np.mean((pred[list(perm)] - true) ** 2))
        best = min(best, mse)
    return best


def evaluate(cfg: Config, sim_cfg: SourceLocConfig, model: FlowBEDModel, key) -> dict:
    prior = SourceLocPrior(K=cfg.k_sources, prior_std=cfg.prior_std)
    eval_loader = make_eval_loader(prior, n_episodes=cfg.n_eval_episodes,
                                    batch_size=cfg.n_eval_episodes, seed=cfg.seed + 1)
    eval_theta = jnp.asarray(next(iter(eval_loader)))  # (N, K, 2)

    per_episode_mse = []
    rollouts = []
    for i in tqdm(range(eval_theta.shape[0]), desc="Evaluating"):
        key, k = jax.random.split(key)
        theta_true = eval_theta[i]
        theta_true_sorted = sort_sources_by_amplitude(theta_true, sim_cfg)
        result = run_rollout(cfg.solver, model, theta_true_sorted, k, sim_cfg,
                              cfg.num_particles, cfg.num_design_steps, cfg.theta_dim, cfg.prior_std)
        posterior_mean = np.asarray(result.z_ensemble[-1].mean(axis=0))
        mse = best_permutation_mse(posterior_mean, np.asarray(theta_true_sorted.reshape(-1)), cfg.k_sources)
        per_episode_mse.append(mse)
        if i < cfg.n_viz_episodes:
            rollouts.append((theta_true_sorted, result))

    metrics = {
        "mean_posterior_mse": float(np.mean(per_episode_mse)),
        "median_posterior_mse": float(np.median(per_episode_mse)),
        "solver": cfg.solver,
        "num_design_steps": cfg.num_design_steps,
        "num_particles": cfg.num_particles,
    }
    return {"metrics": metrics, "per_episode_mse": per_episode_mse, "rollouts": rollouts}


# %%
key, eval_key = jax.random.split(key)
eval_out = evaluate(cfg, sim_cfg, model, eval_key)
print("Evaluation metrics:", eval_out["metrics"])
with open(run_dir / "eval_metrics.json", "w") as f:
    json.dump(eval_out["metrics"], f, indent=2)


# %% [markdown]
# ## 8. Visualisations: trajectories, EIG proxy, posterior samples, solver comparison
#
# Each plot is shown inline first, then saved to `run_dir / "plots"`.

# %%
def plot_trajectory(theta_true_sorted: jnp.ndarray, result: RolloutResult, cfg: Config, tag: str):
    theta_true = np.asarray(theta_true_sorted).reshape(cfg.k_sources, 2)
    z_ensemble = np.asarray(result.z_ensemble)                          # (T+1, M, D)
    mean_path = z_ensemble.mean(axis=1).reshape(-1, cfg.k_sources, 2)   # (T+1, K, 2)
    designs = np.asarray(result.designs)                                # (T, 2)
    T = designs.shape[0]

    fig, ax = plt.subplots(figsize=(8, 7))
    ax.scatter(theta_true[:, 0], theta_true[:, 1], c="red", marker="*", s=300,
               label="True source(s)", zorder=5)
    ax.plot(designs[:, 0], designs[:, 1], "bo-", alpha=0.9, markersize=5, label="Designs $x_t$")

    for k in range(cfg.k_sources):
        alphas = np.linspace(0.15, 1.0, mean_path.shape[0])
        sizes = np.linspace(10, 140, mean_path.shape[0])
        for i in range(mean_path.shape[0]):
            ax.scatter(mean_path[i, k, 0], mean_path[i, k, 1], c="green", alpha=alphas[i],
                       s=sizes[i], marker="X",
                       label=(rf"Ensemble mean $\bar z_t$ (src {k+1})" if i == mean_path.shape[0] - 1 else None))
        ax.plot(mean_path[:, k, 0], mean_path[:, k, 1], color="green", alpha=0.4, lw=1)

    ax.axhline(0, color="gray", ls="--", alpha=0.4)
    ax.axvline(0, color="gray", ls="--", alpha=0.4)
    ax.set_title(f"CFM-BED Trajectory ({tag}, solver={cfg.solver}, T={T})")
    ax.legend(); ax.grid(alpha=0.3)
    fig.tight_layout()
    return fig


def plot_eig(result: RolloutResult, tag: str):
    eig = np.asarray(eig_per_step(result.z_ensemble))
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.bar(range(1, len(eig) + 1), eig, color="teal", alpha=0.8)
    ax.set_title(f"Ensemble-contraction EIG proxy per step ({tag})")
    ax.set_xlabel("Design step"); ax.set_ylabel(r"$H(z_{t}) - H(z_{t+1})$")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    return fig


def plot_posterior_scatter(theta_true_sorted: jnp.ndarray, result: RolloutResult, cfg: Config, tag: str):
    theta_true = np.asarray(theta_true_sorted).reshape(cfg.k_sources, 2)
    final = np.asarray(result.z_ensemble[-1]).reshape(-1, cfg.k_sources, 2)  # (M, K, 2)
    fig, ax = plt.subplots(figsize=(6, 6))
    colors = plt.cm.tab10(np.linspace(0, 1, cfg.k_sources))
    for k in range(cfg.k_sources):
        ax.scatter(final[:, k, 0], final[:, k, 1], s=15, alpha=0.5, color=colors[k],
                   label=f"Posterior samples (src {k+1})")
    ax.scatter(theta_true[:, 0], theta_true[:, 1], c="red", marker="*", s=300,
               label="True source(s)", zorder=5)
    ax.set_title(f"Posterior $p(\\theta \\mid h_T)$ ensemble at t=1 ({tag})")
    ax.legend(); ax.grid(alpha=0.3)
    fig.tight_layout()
    return fig


def plot_solver_comparison(model: FlowBEDModel, theta_true_sorted: jnp.ndarray, cfg: Config,
                            sim_cfg: SourceLocConfig, key, tag: str):
    """Rolls out the same episode under all available solvers and compares final
    posterior-mean error vs. number of vector-field evaluations (a cost/accuracy plot)."""
    solvers = ["euler", "midpoint"] + (["dopri5"] if _HAS_DIFFRAX else [])
    errs, nfes = [], []
    for solver in solvers:
        key, k = jax.random.split(key)
        result = run_rollout(solver, model, theta_true_sorted, k, sim_cfg,
                              cfg.num_particles, cfg.num_design_steps, cfg.theta_dim, cfg.prior_std)
        pmean = np.asarray(result.z_ensemble[-1].mean(axis=0))
        err = best_permutation_mse(pmean, np.asarray(theta_true_sorted.reshape(-1)), cfg.k_sources)
        errs.append(err); nfes.append(result.nfe)

    fig, ax = plt.subplots(figsize=(6, 5))
    ax.scatter(nfes, errs, s=80)
    for s, x, y in zip(solvers, nfes, errs):
        ax.annotate(s, (x, y), textcoords="offset points", xytext=(6, 4))
    ax.set_xlabel("Vector-field evaluations (NFE)"); ax.set_ylabel("Posterior-mean MSE (best perm.)")
    ax.set_title(f"Solver comparison ({tag})")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    return fig


# %%
for i, (theta_true_sorted, result) in enumerate(eval_out["rollouts"]):
    tag = f"ep{i}"

    fig = plot_trajectory(theta_true_sorted, result, cfg, tag)
    plt.show()
    fig.savefig(run_dir / "plots" / f"trajectory_{tag}.png", dpi=150)
    plt.close(fig)

    fig = plot_eig(result, tag)
    plt.show()
    fig.savefig(run_dir / "plots" / f"eig_{tag}.png", dpi=150)
    plt.close(fig)

    fig = plot_posterior_scatter(theta_true_sorted, result, cfg, tag)
    plt.show()
    fig.savefig(run_dir / "plots" / f"posterior_{tag}.png", dpi=150)
    plt.close(fig)

    key, sk = jax.random.split(key)
    fig = plot_solver_comparison(model, theta_true_sorted, cfg, sim_cfg, sk, tag)
    plt.show()
    fig.savefig(run_dir / "plots" / f"solver_comparison_{tag}.png", dpi=150)
    plt.close(fig)

print(f"All artefacts saved under: {run_dir}")
